# name: Deploy Strapi on Proxmox Server

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Deploy to server
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.STRAPI_HOST }}
#         username: ${{ secrets.STRAPI_USERNAME }}
#         key: ${{ secrets.STRAPI_PK }}
#         script: |
#           cd /var/www/strapi
#           git pull origin main
#           cd backend
#           npm install --production
#           npm run build
#           pm2 restart strapi